### PR TITLE
Cortex-M backend: Prerequiste changes to export mv3/mv2 targetting CMSIS-NN backend

### PR DESCRIPTION
**Pull request by psiddh**
### Summary
  This PR correctly identifies that ConvertToCortexMPass inherits from XNNPACKPass and properly passes it the exported_program() argument:

  - ReplaceQuantNodesPass → issubclass(XNNPACKPass) = False → instantiated as pass_cls()
  - ConvertToCortexMPass → issubclass(XNNPACKPass) = True → instantiated as pass_cls(exported_program()) ✓
  - QuantizedOpFusionPass → issubclass(XNNPACKPass) = False → instantiated as pass_cls()

[PLEASE REMOVE] If this PR closes an issue, please add a `Fixes #<issue-id>` line.

[PLEASE REMOVE] If this PR introduces a fix or feature that should be the upcoming release notes, please add a "Release notes: <area>" label. For a list of available release notes labels, check out [CONTRIBUTING.md's Pull Requests](https://github.com/pytorch/executorch/blob/main/CONTRIBUTING.md#pull-requests).

### Test plan
python3 -m examples.arm.aot_arm_compiler     -m mv2     --target=ethos-u55-128     --quantize     --enable_qdq_fusion_pass     --output=./output/mv2_cmsis

Without this change, the error would be 
_File "/home/sidart/executorch/examples/arm/aot_arm_compiler.py", line 808, in transform_for_cortex_m_backend
else pass\_cls()
TypeError: XNNPACKPass.__init__() missing 1 required positional argument: 'exported_program'"_

cc @digantdesai @freddan80 @per @zingo @oscarandersson8218 @mansnils @Sebastian-Larsson @robell

### CODE REVIEW

**Comment by AdrianLundell** [comment]
Nice to get cortex-m support in the aot-arm-compiler! Have you tried using the cortex-m pass manager here instead of listing all passes separately? You also need to make sure that you do not decompose a couple of ops to get the same behaviour as in the unittests.
