### ISSUE TITLE
The ExecuTorch SwiftPM binary distribution (v0.7.0) fails to load the "forward" method from exported PTE models with **Error 32 (NotFound)**, while the same PTE files work perfectly with the Python ExecuTorch runtime (v0.7.0)

### ISSUE THREAD

**Issue by andytriboletti** [pytorch/executorch#14809]
### 🐛 Describe the bug

# ExecuTorch SwiftPM Binary Distribution Bug Report

## Summary

The ExecuTorch SwiftPM binary distribution (v0.7.0) fails to load the "forward" method from exported PTE models with **Error 32 (NotFound)**, while the same PTE files work perfectly with the Python ExecuTorch runtime (v0.7.0).

## Environment

- **Platform**: macOS 26.0.1 (Apple Silicon M1/M2)
- **Xcode**: 26.0.1
- **ExecuTorch Python**: 0.7.0 (pip package)
- **ExecuTorch SwiftPM**: 0.7.0 (branch: swiftpm-0.7.0)
- **Model**: SmolLM-135M exported with LLM exporter
- **Export Command**:
```bash
python -m executorch.examples.models.llama.export_llama \
  --model smollm2 \
  -X --pt2e_quantize xnnpack_dynamic \
  --max_seq_length 128 \
  --params params.json \
  -n smollm2_simple.pte \
  -o . \
  -v
```

### What Works (Python Runtime)

```python
from executorch.extension.pybindings.portable_lib import _load_for_executorch_from_buffer

with open("smollm2_simple.pte", "rb") as f:
    module = _load_for_executorch_from_buffer(f.read())

# This works perfectly
tokens = torch.tensor([[1, 72, 101, 108, 108, 111]], dtype=torch.long)
result = module.forward([tokens])
print(result[0].shape)  # Output: torch.Size([1, 49152])
```

**Result**: ✅ Works perfectly, generates coherent text

### What Fails (C++ SwiftPM Runtime)

```objc
// Load model
auto module = std::make_unique<torch::executor::Module>(modelPath, ...);
auto load_err = module->load();
// load_err == Error::Ok ✅

// Try to load forward method
auto load_method_err = module->load_method("forward");
// load_method_err == Error::NotFound (32) ❌

// Try to execute forward
std::vector<executorch::runtime::EValue> inputs;
inputs.emplace_back(*input_tensor);
auto result = module->forward(inputs);
// result.error() == Error::NotFound (32) ❌

// Try execute("forward", ...)
auto result2 = module->execute("forward", inputs);
// result2.error() == Error::NotFound (32) ❌
```

**Result**: ❌ Error 32 (NotFound) - method cannot be loaded or executed

### 1. Method Exists in Metadata

```objc
auto method_names = module->method_names();
// Returns: ["enable_dynamic_shape", "use_sdpa_with_kv_cache", "get_n_layers", 
//           "get_eos_ids", "get_max_seq_len", "get_vocab_size", "get_bos_id", 
//           "get_max_context_len", "use_kv_cache", "forward"]
```

The "forward" method is listed in `method_names()`, but cannot be loaded.

### 2. Method Metadata is Accessible

```objc
auto meta_result = module->method_meta("forward");
// meta_result.ok() == true ✅

auto meta = meta_result.get();
// meta.num_inputs() == 1
// meta.input_tensor_meta(0).dtype() == ScalarType::Long (4)
// meta.input_tensor_meta(0).sizes() == [1, dynamic]
// meta.num_outputs() == 1
// meta.output_tensor_meta(0).dtype() == ScalarType::Float (6)
// meta.output_tensor_meta(0).sizes() == [1, 49152]
```

Metadata is accessible and shows correct input/output signatures.

### 3. All Operators Are Present

We verified that all required operators are present in the SwiftPM binaries by:
- Extracting operator list from PTE using `gen_oplist.py`
- Confirming all operators exist in `kernels_optimized` and `backend_xnnpack`
- Disabling custom operator registration → error remains 32 (not 20/OperatorMissing)

### 4. KV Cache Methods Also Fail

```objc
auto kv_result = module->execute("use_kv_cache", {true});
// kv_result.error() == Error::InvalidArgument (18) ❌
```

Helper methods added by LLM exporter also fail.

### ✅ Tried: Custom Operator Registration
- Generated `selected_operators.yaml` from PTE
- Created `RegisterCodegenUnboxedKernelsEverything.cpp`
- Linked all required kernels (optimized, xnnpack, custom, quantized)
- **Result**: Same error (32)

### ✅ Tried: Different Input Signatures
Attempted all possible input combinations:
- `[ids:int64 1xL]`, `[ids:int32 1xL]`
- `[ids:int64 L]`, `[ids:int32 L]`
- `[ids:int64, mask:int64]`, `[ids:int32, mask:int32]`
- `[ids:int64, seq_len:int32]`, `[ids:int32, seq_len:int32]`
- `[ids:int64, positions:int64]`, `[ids:int32, positions:int32]`
- Fixed sequence lengths: K ∈ {16, 32, 64, 128, 256}
- **Result**: All return error 32

### ✅ Tried: Different Module Loading Patterns
- Owner module (path-based): `Module(path, ...)`
- Allocator-backed module: `Module(path, ..., allocator)`
- Explicit `load_forward()` calls
- **Result**: All return error 32

### ✅ Tried: Version Alignment
- Downgraded Python to 0.4.0 → same error
- Upgraded Python to 0.7.0 → works in Python, fails in C++
- **Result**: Python works, C++ fails regardless of version

## Root Cause Hypothesis

The SwiftPM binary distribution appears to have a fundamental incompatibility with PTE files exported by the Python ExecuTorch 0.7.0 package. Specifically:

1. **Method Plan Loading**: The C++ runtime cannot load method plans from PTE files, even though:
   - The method exists in metadata
   - All operators are present
   - The Python runtime loads the same file successfully

2. **SwiftPM Branch Discrepancy**: The `swiftpm-0.7.0` branch doesn't exist in the official PyTorch/ExecuTorch repository. The latest official SwiftPM branch is `swiftpm-0.4.0`, suggesting the 0.7.0 binaries may be:
   - An unofficial build
   - An outdated/incomplete build
   - Missing critical runtime components

## Workaround

We implemented a **Python subprocess bridge** that:
1. Spawns Python process running ExecuTorch
2. Communicates via JSON over stdin/stdout
3. Uses the working Python runtime for inference
4. Adds ~1-5ms IPC overhead per token (negligible)

**Result**: ✅ Fully functional, generates coherent text

## Expected Behavior

The C++ SwiftPM runtime should be able to:
1. Load the "forward" method: `load_method("forward")` → `Error::Ok`
2. Execute forward pass: `forward(inputs)` → valid output tensor
3. Match Python runtime behavior exactly

## Actual Behavior

- `load_method("forward")` → `Error::NotFound (32)`
- `forward(inputs)` → `Error::NotFound (32)`
- `execute("forward", inputs)` → `Error::NotFound (32)`

## Reproduction Steps

1. **Export model** (Python):
```bash
python -m executorch.examples.models.llama.export_llama \
  --model smollm2 \
  -X --pt2e_quantize xnnpack_dynamic \
  --max_seq_length 128 \
  --params params.json \
  -n model.pte
```

2. **Test in Python** (works):
```python
from executorch.extension.pybindings.portable_lib import _load_for_executorch_from_buffer
import torch

with open("model.pte", "rb") as f:
    module = _load_for_executorch_from_buffer(f.read())

tokens = torch.tensor([[1, 2, 3]], dtype=torch.long)
result = module.forward([tokens])
print("Success:", result[0].shape)
```

3. **Test in C++ with SwiftPM** (fails):
```objc
#import <executorch/extension/module/module.h>

auto module = std::make_unique<torch::executor::Module>(modelPath);
module->load();

auto result = module->load_method("forward");
// result == Error::NotFound (32)
```

## Additional Information

- **PTE File Size**: 238 MB
- **Model Architecture**: SmolLM-135M (30 layers, 9 heads, vocab_size=49152)
- **Quantization**: XNNPACK dynamic quantization
- **Backend**: XNNPACK + optimized kernels
- **Platform**: macOS (arm64)

## Questions

1. Is the `swiftpm-0.7.0` branch an official release?
2. Are there known incompatibilities between Python-exported PTEs and SwiftPM binaries?
3. Should we use a different export path for SwiftPM compatibility?
4. Is there a recommended way to debug Error::NotFound (32) in method loading?

## Files Available

- `smollm2_simple.pte` - Exported model file (works in Python, fails in C++)
- `selected_operators.yaml` - Extracted operator list
- Full Xcode project with reproduction case

Happy to provide any additional information or test patches!

### Versions

(venv) andytriboletti@macbookpro alientavern-v2 % python collect_env.py

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 26.0.1 (arm64)
GCC version: Could not collect
Clang version: 17.0.0 (clang-1700.3.19.1)
CMake version: version 4.1.2
Libc version: N/A

Python version: 3.13.7 (main, Aug 14 2025, 11:12:11) [Clang 17.0.0 (clang-1700.3.19.1)] (64-bit runtime)
Python platform: macOS-26.0.1-arm64-arm-64bit-Mach-O
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
Is XPU available: N/A
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] No relevant packages
[conda] Could not collect

cc @shoumikhin @cbilgin

**Comment by shoumikhin** [comment]
Does "-all_load" linker flag help to resolve that?
Also, feel free to try version "1.0.0"

**Comment by andytriboletti** [comment]
-all_load:
When trying -all_load I get a compilation error - 88 duplicate symbols.

-1.0.0:
-When trying 1.0.0:
- The `swiftpm-1.0.0` branch exists but isn't fully configured yet
- Missing package products (executorch, kernels_optimized, backend_mps, etc.)
- Can you please link to instructions for 1.0.0 if they exist?

Thank you. 

I am able to move onto other issues in my project cause I have it working with the python interface in macos, and I found a lite mistral 150 model linked from reddit I now use that responds quickly and adequately for my purposes.

**Comment by shoumikhin** [comment]
@andytriboletti are you still facing issues for the 1.0.0 packages? Please let me know how to reproduce it if so. Thanks.

**Comment by andytriboletti** [comment]
Hi @shoumikhin,

**Update: Still not working with v1.0.0 - now failing in both C++ AND Python**

### Current Error
```
[method.cpp:732] Missing operator: [11] llama::custom_sdpa.out
[method.cpp:975] There are 90 instructions don't have corresponding operator registered
Error: loading method forward failed with error 0x14
```

### Root Cause
The model was exported with **custom operators** via `optimum-executorch`:
- `llama::custom_sdpa.out` (custom attention)
- Custom KV cache operators
- These operators are **not included** in the SwiftPM distribution

### Questions
1. Does SwiftPM v1.0.0 include custom SDPA operators?
2. What export configuration should we use for SwiftPM compatibility?
   - `attn_implementation="eager"` instead of `"custom_sdpa"`?
   - `use_custom_kv_cache=False`?
   - No quantization?
3. How do we register custom operators with SwiftPM builds?

### What I Need
Either:
- Instructions for exporting **SwiftPM-compatible models** (without custom ops), OR
- Instructions for **building SwiftPM with custom operators**

Thanks!

**Comment by andytriboletti** [comment]
After a couple days work, I got it working great with 1.0 and no python, with an optimized smolm2 model responding very fast on macos. It answered my question 'what is the capital of france?' reliably always containing Paris in my testing. 

I will generate a summary of my findings and post a link after I take a short break. I used AugmentCode GPT-5 as my coding assistant. It was pretty tough for me to get it working.

**Comment by mergennachin** [comment]
@andytriboletti -- glad that you got it working.

what did you do to make it work? any feedback on the documentation that is not obvious?

**Comment by andytriboletti** [comment]
Blog post about "ExecuTorch on macOS with XNNPACK: from OperatorMissing to fast inference": https://blog.greenrobot.com/2025/10/29/executorch-on-macos-with-xnnpack-from-operatormissing-to-fast-inference/

Video of it running on macOS:
https://www.youtube.com/shorts/KHXUIlop-1w

Text of article:

# ExecuTorch on macOS with XNNPACK: from OperatorMissing to fast inference

This is a write‑up of what finally made ExecuTorch 1.0.0 LLMs run fast on macOS with the XNNPACK backend, after days of chasing `Error::OperatorMissing` and build issues.

## TL;DR

- Exported with `export_llm` using XNNPACK + TorchAO 8da4w
- Built and included `kernels_torchao.xcframework` (TorchAO ops) in the app
- Ensured ExecuTorch’s static operator registrations run at runtime by linking the static libs with `-Wl,-force_load,<libpath>` (per lib)
- Avoided duplicate linking by not also adding those `.xcframework`s in the “Link Binary With Libraries” build phase
- Removed `-all_load` (caused huge duplicate symbols) and fixed malformed linker flags
- Built via the Xcode workspace (Pods) instead of the standalone project

## Symptoms

- Loading an XNNPACK PTE failed with: `Error::OperatorMissing (20)`
- The PTE contained `llama::custom_sdpa.out` and `llama::update_cache.out`, but runtime registry didn’t have them
- Portable model also failed prefill with `Error::NotSupported (16)` before fixes
- Adding `-all_load` “fixed” registrations but exploded into thousands of duplicate symbols (Skia, etc.)

## Root cause

ExecuTorch’s custom operators (e.g. LLM `llama::*` ops, TorchAO ops) are registered via static initializers created by `EXECUTORCH_LIBRARY(...)`. When linking static libraries inside `.xcframework`s on Apple, those initializers may not be pulled in unless you force the linker to load the objects that contain them.

If you simply add the `.xcframework`s and no code references the contained symbols, the linker can drop them — the registrations don’t execute — and you get `OperatorMissing` at runtime.

## The fix (linker + layout)

1) Choose a single, consistent way to link

- Do NOT both:
  - add the ExecuTorch `.xcframework`s to the target’s “Link Binary With Libraries” phase, and
  - also `-force_load` their inner static `.a` libs in Other Linker Flags.
- Pick one. We picked `-force_load` for the inner `.a` files and removed the `.xcframework` items from “Link Binary With Libraries” to avoid duplicates.

2) Force‑load the specific static libraries that contain registrations

For our XNNPACK + LLM + TorchAO build, we needed to force‑load at least these libs (adjust path roots if different):

```
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/executorch.xcframework/macos-arm64/libexecutorch_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/executorch_llm.xcframework/macos-arm64/libexecutorch_llm_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/kernels_llm.xcframework/macos-arm64/libkernels_llm_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/kernels_optimized.xcframework/macos-arm64/libkernels_optimized_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/kernels_quantized.xcframework/macos-arm64/libkernels_quantized_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/kernels_torchao.xcframework/macos-arm64/libkernels_torchao_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/backend_xnnpack.xcframework/macos-arm64/libbackend_xnnpack_macos.a
-Wl,-force_load,$(SRCROOT)/ExecuTorchFrameworks/threadpool.xcframework/macos-arm64/libthreadpool_macos.a
```

Notes:
- Use the single‐token `-Wl,-force_load,<path>` form in Xcode’s “Other Linker Flags”. It’s much less error‑prone than manually sprinkling `-Xlinker` tokens.
- Do not use `-all_load` — it can pull in everything and cause thousands of duplicate symbols with other deps (e.g., Skia).

3) Add header search paths (if you import ObjC headers from ExecuTorch)

```
$(SRCROOT)/ExecuTorchFrameworks/executorch.xcframework/macos-arm64/Headers
$(SRCROOT)/ExecuTorchFrameworks/executorch_llm.xcframework/macos-arm64/Headers
```

4) Build with the workspace

- Use `AlienTavernMobile.xcworkspace` (or your workspace) so CocoaPods products resolve. Building only the `.xcodeproj` can mislead with unrelated missing libs (e.g., DoubleConversion) and isn’t how the app is normally linked.

## TorchAO: include kernels_torchao

When exporting with TorchAO 8da4w, the graph includes `torchao::quantize_affine`/`dequantize_affine`/`choose_qparams` etc. Those kernels are not in `kernels_quantized` — you need `kernels_torchao` too.

How we built the Apple frameworks (including TorchAO):

```
cd <executorch_checkout>
./scripts/build_apple_frameworks.sh --Release --torchao
```

Then we copied the XCFramework(s) into the app’s tree (e.g., `ExecuTorchFrameworks/`) and added the `-force_load` entry for `kernels_torchao` as shown above.

## Verifying the operators

Two good checks that caught the issue:

1) Inspect the PTE to list operators in the plan (Python, optional):
- Convert PTE flatbuffer to JSON and inspect the operator table
- Cross‑check whether those ops should be provided by kernels you linked (e.g., TorchAO, LLM custom ops)

2) Inspect the runtime registry at startup (C++):
- Log whether the registry contains the ops you need (e.g., `llama::custom_sdpa.out`, `llama::update_cache.out`)
- If missing, your registrations didn’t run — a linking/initializer issue

## Common pitfalls we hit

- Malformed `OTHER_LDFLAGS`: a stray `-Xlinker` token on its own makes Xcode treat it as an input path (`…/mobile/macos/-Xlinker` not found)
- Using `-all_load`: caused 6k+ duplicate symbols via transitive static libs (Skia, etc.)
- Adding `.xcframework`s to the Frameworks phase AND also `-force_load`ing their libs: double‑linking and duplicate symbols
- Forgetting to include `kernels_torchao` when exporting with TorchAO 8da4w
- Building the `.xcodeproj` instead of the workspace: spurious CocoaPods missing‑lib warnings

## Minimal troubleshooting checklist

1) Confirm the PTE contains only ops you know are provided by the set of ExecuTorch libs you’re linking
2) At runtime, log `registry_has_op_function("llama::custom_sdpa.out")` and `registry_has_op_function("llama::update_cache.out")`
3) If missing, fix linking so static initializers run:
   - Remove `.xcframework`s from “Link Binary With Libraries” for the ExecuTorch libs you will `-force_load`
   - Add `-Wl,-force_load,<path>` for each required `.a` inside those `.xcframework`s
   - Remove `-all_load` and fix any stray `-Xlinker` tokens
4) Ensure `kernels_torchao` is included when using TorchAO quantization
5) Build the workspace, not the project

## Why this works

The `EXECUTORCH_LIBRARY(namespace, name, fn)` macros emit static initializers that register kernels when their object files are linked and loaded. If the linker never pulls in the object containing the initializer, the registration never runs. `-force_load` guarantees the linker brings in those objects even if nothing directly references them, and the registrations execute.

## Suggested docs improvements

- Provide a “linker recipe” for Apple static linking that includes:
  - The list of `.a` libs to include for common scenarios (portable, XNNPACK, LLM, TorchAO)
  - A warning against mixing the Frameworks phase with `-force_load` for the same `.xcframework`
  - Use of `-Wl,-force_load,<path>` and avoiding `-all_load`
- Add an explicit note that TorchAO exports require `kernels_torchao` at runtime
- Include a small runtime snippet to validate op registration (e.g., `registry_has_op_function`)
- Include a “PTE inspection” tip for debugging OperatorMissing (flatbuffer → JSON → list ops)

## References

- ExecuTorch 1.0.0
- XNNPACK backend
- TorchAO 8da4w export path via `export_llm`
- GitHub issue: https://github.com/pytorch/executorch/issues/14809

**Comment by andytriboletti** [comment]
Feedback on docs (what wasn’t obvious) (From coding agent AugmentCode GPT-5 in text response after generating that markdown post) in answer to your question

Apple linker recipe for ExecuTorch static initializers:
-Explicitly document that EXECUTORCH_LIBRARY registration requires the relevant object files to be linked and loaded, which may need -Wl,-force_load for static libs inside XCFrameworks.
-Warn against mixing “Link Binary With Libraries” with -force_load for the same XCFrameworks (double-linking leads to duplicates).
-Recommend avoiding -all_load; it triggers enormous duplicate symbol cascades with other static deps.

TorchAO requirement:
-When exporting with TorchAO (e.g., 8da4w), you must include kernels_torchao at runtime. This wasn’t clear; many folks will link kernels_quantized but miss kernels_torchao.

Troubleshooting checklist:
-Show how to inspect a PTE’s operator list (flatbuffer → json) and how to check registry_has_op_function at runtime for required ops (e.g., llama::custom_sdpa.out).
-Provide a canonical list of libs to link for common targets:
--Portable
--XNNPACK
--XNNPACK + LLM
--XNNPACK + LLM + TorchAO

Linker flag syntax:
-Recommend the single-token -Wl,-force_load, form in Xcode to avoid stray -Xlinker tokens being misparsed as input files.

**Comment by shoumikhin** [comment]
@andytriboletti that's awesome! Thank you so much for the details on your journey. Is it opensource, btw?
Curious if you've seen the [Linkage](https://docs.pytorch.org/executorch/1.0/using-executorch-ios.html#linkage) docs?
Fwiw, you may like to use `.xcconfig` files with linker flags declaration to make it a bit easier.

**Comment by andytriboletti** [comment]
This app is Alien Tavern, a swiss army knife utility for dating and networking, and a dating app for alien enthusiasts. I could work on making the executorch macos component open source. Maybe make a PR to react native executorch with macos support? I am currently looking for work, or looking to have a profitable business. If I became employed or made money, I may open source the whole alien tavern social network I'm working on, but before then probably no.

**Comment by shoumikhin** [comment]
@andytriboletti got it! Have you see one [demo app](https://github.com/pytorch/executorch/tree/main/examples/demo-apps/react-native/rnllama) that we have using React Native? Not sure if it's up to date though, but feel free to take a look and possibly make it run on macOS.

**Comment by andytriboletti** [comment]
I had AugmentCode create open-source code for a React Native ExecuTorch base setup for a macOS project. It is based on my closed-source project, where it was working properly.

https://github.com/greenrobotllc/react-native-executorch-macos

**Comment by nil-is-all** [comment]
@shoumikhin closing this issue and marking as user-resolved. @andytriboletti feel free to re-open this issue if further discussion is necessary.
