### PR TITLE
Raise inoperative error guards in ExportSession, XNNPACK node_visitor, and Samsung conv1d

### PR DESCRIPTION
**Pull request by AxelNoun**
### Summary

Four error-guard sites construct a failure that cannot actually fire. This PR inserts the missing `raise` (or replaces an always-true `assert` with the file's existing `check_or_raise`) so the documented failure mode is the one callers see.

| File | What happens today | Reachability |
| --- | --- | --- |
| `export/export.py` `ExportSession.print_delegation_info`, empty lowering-stage set | `RuntimeError(...)` is built and discarded; `lowering_stage[0]` then raises `IndexError: list index out of range` | **Reachable.** `ExportSession` is in `executorch.export.__all__` and is `@experimental`. Calling `print_delegation_info()` on a session whose pipeline has no lowering stage hits this path. |
| `export/export.py` `print_delegation_info`, lowering stage listed but not run | `RuntimeError(...)` is built and discarded; `None.get_context(...)` then raises `AttributeError: 'NoneType' object has no attribute 'get_context'` | **Reachable.** A pipeline that lists `TO_EDGE_TRANSFORM_AND_LOWER` (or `TO_BACKEND`) but has not run that stage hits this path. |
| `backends/xnnpack/operators/node_visitor.py` per-channel axis `else` | `assert f"Unsupported weight per channel quantization axis ..."` — the f-string is always truthy, so the assertion never fires. An `assert` would also disappear under `python -O`. | **Not reachable on a normal export.** The only call that passes `swap_in_out_for_weights=True` is `backends/xnnpack/operators/op_conv2d.py:102`, and that visitor already `check_or_raise`s the axis to `0` (depthwise) or `1` (transpose) before `define_tensor`. This change restores a guard that can actually raise if that `else` is ever entered; it does not fix a mis-serialized `.pte` on the current conv2d path. |
| `backends/samsung/_passes/conv1d_to_conv2d.py` `update_kernel` `else` | `RuntimeError("Weight of 1d conv should be constant tensor or Parameter obj")` is built and discarded; `weight_node.meta["val"]` is still unsqueezed. | **Not reachable on a normal Parameter / lifted-constant / buffer conv1d export.** Those cases are handled by the preceding branches (the buffer branch was added on `main` by #22725). The `else` is the leftover for a weight that is none of those. This change only makes that documented `RuntimeError` actually raise if the branch is entered. |

`print_delegation_info` also corrects the message "atleast" → "at least".

### Test plan

Tests are included only for the two reachable sites (F3a). There is intentionally no test for the XNNPACK `else` (F2) and none for the Samsung `else` (F3b): both are unreachable on a normal export, and a test that injects that state would exercise a situation the production callers do not produce.

`export/tests/test_print_delegation_info.py` covers the two `ExportSession` guards (`export/tests` is already in `pytest.ini` `testpaths`):

```
pytest export/tests/test_print_delegation_info.py
```

On `6755ea388ce6d2249d26f568c286a153ccba4883`:

- unpatched: `IndexError: list index out of range` and `AttributeError: 'NoneType' object has no attribute 'get_context'`
- patched: both tests pass with `RuntimeError` and the documented messages

F2: `op_conv2d.py` already rejects `axis ∉ {0, 1}` before `define_tensor`. No AST test and no injected-axis test is in this PR.

F3b: a normal Parameter / lifted-constant / buffer conv1d does not enter the `else`. No monkeypatch test is in this PR. The change only restores the `RuntimeError` the source already spelled out, if that branch is ever entered.

A separate, two-line cleanup (duplicate dataclass fields in `examples/models/llama/model_args.py` and `exir/serde/schema.py`) is available as `differe-f4.patch` if a follow-up PR is wanted; it is not part of this change.

### CODE REVIEW

**Comment by AxelNoun** [comment]
> @pytorchbot label "release notes: none"

@pytorchbot label "release notes: none"

**Comment by nil-is-all** [comment]
Thanks @AxelNoun, running CI again

**Comment by AxelNoun** [comment]
> Thanks @AxelNoun, running CI again

Thanks ! @nil-is-all

**Comment by AxelNoun** [comment]
Thanks @nil-is-all. I triaged the 6 failures on 12c3858. All of them are already present on the merge base df6147a, none come from this PR:

- `pull / unittest{,-editable}` (linux, macos): 11 failures + 2 collection errors, all `ModuleNotFoundError: No module named 'pyre_extensions'` in `backends/native/test` and `exir/native/test`. Introduced by #22762, fixed on main by #22802. The same 13 test ids fail on df6147a, and the passing count goes 2800 → 2802: the two tests this PR adds run and pass.
- `Test QNN Windows MSVC build` (arm64, x64): MSVC errors in `extension/llm/runner/model_metadata.h`, fixed on main by #22754. This PR changes four error guards in three Python files and adds one Python test: no C++, no QNN, no build files.

The workflows check out the PR head rather than a merge with main, so re-running on 12c3858 would reproduce the same six reds, since the fixes only landed after df6147a. Happy to merge main in (500849ba5b is green on all of these) if you'd prefer a green run; otherwise this should be reviewable as is. @digantdesai, could you take a look?

**Comment by nil-is-all** [comment]
> Thanks @nil-is-all. I triaged the 6 failures on [12c3858](https://github.com/pytorch/executorch/commit/12c3858f4155c3cd271cee4046870e739919fc09). All of them are already present on the merge base [df6147a](https://github.com/pytorch/executorch/commit/df6147afadf106a0ef3a74f65d80b5c589e63e44), none come from this PR:
> 
> * `pull / unittest{,-editable}` (linux, macos): 11 failures + 2 collection errors, all `ModuleNotFoundError: No module named 'pyre_extensions'` in `backends/native/test` and `exir/native/test`. Introduced by [Add ReplaceCopyWithAliasPass (#22762) #22762](https://github.com/pytorch/executorch/pull/22762), fixed on main by [Remove `pyre_extensions` dependency from native preprocessing #22802](https://github.com/pytorch/executorch/pull/22802). The same 13 test ids fail on [df6147a](https://github.com/pytorch/executorch/commit/df6147afadf106a0ef3a74f65d80b5c589e63e44), and the passing count goes 2800 → 2802: the two tests this PR adds run and pass.
> * `Test QNN Windows MSVC build` (arm64, x64): MSVC errors in `extension/llm/runner/model_metadata.h`, fixed on main by [Fix model metadata readers on MSVC #22754](https://github.com/pytorch/executorch/pull/22754). This PR changes four error guards in three Python files and adds one Python test: no C++, no QNN, no build files.
> 
> The workflows check out the PR head rather than a merge with main, so re-running on [12c3858](https://github.com/pytorch/executorch/commit/12c3858f4155c3cd271cee4046870e739919fc09) would reproduce the same six reds, since the fixes only landed after [df6147a](https://github.com/pytorch/executorch/commit/df6147afadf106a0ef3a74f65d80b5c589e63e44). Happy to merge main in ([500849b](https://github.com/pytorch/executorch/commit/500849ba5bd2e425a14d379157b87bb2d7c91d4a) is green on all of these) if you'd prefer a green run; otherwise this should be reviewable as is. @digantdesai, could you take a look?

Hi @AxelNoun, I agree the CI failures seem irrelevant. Would like to get a final OK from @digantdesai and then merge. Thanks for the ping

File: backends/xnnpack/operators/node_visitor.py [hunk 1]
```diff
@@ -475,7 +475,10 @@ def define_tensor(  # noqa: C901
             elif quant_params.axis == 1:
                 quant_params.axis = 0
             else:
-                assert f"Unsupported weight per channel quantization axis for depthwise conv2d / conv_transpose2d : {quant_params.axis}, expecting 0 / 1."
+                check_or_raise(
```
Comment (digantdesai) [inline backends/xnnpack/operators/node_visitor.py]: shoudln't we use 'why()'?

**Review by digantdesai — APPROVED** [review]

**Comment by digantdesai** [comment]
Please rebase, and make sure CI is green. Thanks.
